### ISSUE TITLE
Function app template not compatible with default Remix template

### ISSUE THREAD

**Issue by ewalk153** [Shopify/function-examples#460]
## Which template or example

With the cli and then generating a cart transform function, the cart transform function tests fail to run due to a conflict with the vite.config.js file generated by Remix.

## Describe the bug

Error run the project's test, coming from this in the `vite.config.js`

```
export default defineConfig({
  server: {
    port: Number(process.env.PORT || 3000),
    hmr: hmrConfig,
  },
  plugins: [
    remix({
      ignoredRouteFiles: ["**/.*"],
    }),
    tsconfigPaths(),
  ],
  build: {
    assetsInlineLimit: 0,
  },
});
```

It appears the Remix code is attempting to be loaded in the subproject for the extension.

```
failed to load config from /Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/vite.config.js

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: (0 , import_vite_tsconfig_paths.default) is not a function
    at Object.<anonymous> (/Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/vite.config.js:69:44)
```

Adding an empty `vite.config.js` file in the function directory resolves the error. I'm not sure of the other consequences of  adding more than one `vite.config.js` to the project.

## Steps to reproduce
```
npm init @shopify/app@latest
cd your-app-name
npm run dev # to complete setup
npm run shopify generate extension # I picked cart-transform and named it cart-transformer
cd extensions/cart-transformer
npm run test
```

Note: moving `vite.config.js` away fixes the issue with the function tests but breaks Remix.

Output:
```
> cart-transformer@0.0.1 test
> vitest

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
failed to load config from /Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/vite.config.js

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: (0 , import_vite_tsconfig_paths.default) is not a function
    at Object.<anonymous> (/Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/vite.config.js:69:44)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at _require.extensions.<computed> [as .js] (file:///Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-52909643.js:66350:24)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at loadConfigFromBundledFile (file:///Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-52909643.js:66358:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadConfigFromFile (file:///Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-52909643.js:66181:28)



npm ERR! Lifecycle script `test` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: cart-transformer@0.0.1
npm ERR!   at location: /Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/extensions/cart-transformer

~/src/github.com/Shopify/apps/lean-investment-app/extensions/cart-transformer main*
❯ yarn test
yarn run v1.22.19
$ vitest
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
failed to load config from /Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/vite.config.js

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: (0 , import_vite_tsconfig_paths.default) is not a function
    at Object.<anonymous> (/Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/vite.config.js:69:44)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at _require.extensions.<computed> [as .js] (file:///Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-52909643.js:66350:24)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at loadConfigFromBundledFile (file:///Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-52909643.js:66358:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadConfigFromFile (file:///Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-52909643.js:66181:28)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior

When moving the vite.config.js away, we get the following from a newly generated function:
```
yarn run v1.22.19
$ vitest

 DEV  v0.29.8 /Users/ewalker/src/github.com/Shopify/apps/lean-investment-app/extensions/cart-transformer

 ✓ src/run.test.js (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  20:28:52
   Duration  140ms (transform 19ms, setup 0ms, collect 7ms, tests 1ms)


 PASS  Waiting for file changes...
       press h to show help, press q to quit
```

**Comment by ewalk153** [comment]
Fix confirmed:
```
❯ npm init @shopify/app@latest

Welcome. Let’s get started by naming your app project. You can change it later.

?  Your project name?
✔  modern-projection-app

?  Get started building your app:
✔  Start with Remix (recommended)

?  For your Remix template, which language do you want?
✔  JavaScript


╭─ success ─────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                   │
│  modern-projection-app is ready for you to build!                                                                 │
│                                                                                                                   │
│  Next steps                                                                                                       │
│    • Run `cd modern-projection-app`                                                                               │
│    • For extensions, run `npm run generate extension`                                                             │
│    • To see your app, run `npm run dev`                                                                           │
│                                                                                                                   │
│  Reference                                                                                                        │
│    • Shopify docs                                                                                                 │
│    • For an overview of commands, run `npm run shopify app -- --help`                                             │
│                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


~/src/github.com/Shopify/apps 49s
❯ ls
lean-investment-app   modern-projection-app quick-warranty

~/src/github.com/Shopify/apps
❯ cd modern-projection-app

~/src/github.com/Shopify/apps/modern-projection-app main*
❯ npm run dev

> dev
> shopify app dev


To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser
✔ Logged in.


Before proceeding, your project needs to be associated with an app.

?  Create this project as a new app on Shopify?
✔  Yes, create it as a new app

?  App name:
✔  modern-projection-app

✔ Using your default dev store, Quickstart (01b53dbf), to preview your project.
╭─ info ────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                   │
│  Using shopify.app.toml:                                                                                          │
│                                                                                                                   │
│    • Org:             Eric's Test Biz                                                                             │
│    • App:             modern-projection-app                                                                       │
│    • Dev store:       [editedout].myshopify.com                                                           │
│    • Update URLs:     Not yet configured                                                                          │
│                                                                                                                   │
│   You can pass `--reset` to your command to reset your app configuration.                                         │
│                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─ error ───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                   │
│  Port 3457 is not available for serving GraphiQL.                                                                 │
│                                                                                                                   │
│  Choose a different port by setting the `--graphiql-port` flag.                                                   │
│                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


~/src/github.com/Shopify/apps/modern-projection-app main* 21s
❯ npm run shopify generate extension

> shopify
> shopify generate extension

?  Command `generate extension` not found. Did you mean `app generate extension`?
✔  Yes, confirm

╭─ info ────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                   │
│  Using shopify.app.toml:                                                                                          │
│                                                                                                                   │
│    • Org:             Eric's Test Biz                                                                             │
│    • App:             modern-projection-app                                                                       │
│                                                                                                                   │
│   You can pass `--reset` to your command to reset your app configuration.                                         │
│                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

?  Type of extension?
✔  Cart transformer - Function

?  Name your extension:
✔  cart-transformer

?  What would you like to work in?
✔  JavaScript

▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building GraphQL types ...

╭─ success ─────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                   │
│  Your extension was created in extensions/cart-transformer.                                                       │
│                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


~/src/github.com/Shopify/apps/modern-projection-app main* 26s
❯ cd extensions/cart-transformer

~/src/github.com/Shopify/apps/modern-projection-app/extensions/cart-transformer main*
❯ npm run test

> cart-transformer@0.0.1 test
> vitest


 DEV  v0.29.8 /Users/ewalker/src/github.com/Shopify/apps/modern-projection-app/extensions/cart-transformer

 ✓ src/run.test.js (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  09:26:03
   Duration  126ms (transform 18ms, setup 0ms, collect 8ms, tests 1ms)


 PASS  Waiting for file changes...
       press h to show help, press q to quit
```
